/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import { GlobalComponents } from 'vue'

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppHeader: typeof import('./../components/AppHeader.vue')['default']
    AuthCard: typeof import('./../components/auth/AuthCard.vue')['default']
    AvatarUploader: typeof import('./../components/common/AvatarUploader.vue')['default']
    ChatBoard: typeof import('./../components/Chat/ChatBoard.vue')['default']
    CreateFamilyDialog: typeof import('./../components/Family/CreateFamilyDialog.vue')['default']
    EditFamilyDialog: typeof import('./../components/Family/EditFamilyDialog.vue')['default']
    ElCollapse: typeof import('element-plus/es')['ElCollapse']
    ElCollapseItem: typeof import('element-plus/es')['ElCollapseItem']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSkeleton: typeof import('element-plus/es')['ElSkeleton']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    JoinFamilyDialog: typeof import('./../components/Family/JoinFamilyDialog.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    WelfareCard: typeof import('./../components/welfareCard.vue')['default']
    WelfareFilterBar: typeof import('./../components/WelfareFilterBar.vue')['default']
  }
  export interface GlobalDirectives {
    vInfiniteScroll: typeof import('element-plus/es')['ElInfiniteScroll']
  }
}

// For TSX support
declare global {
  const AppHeader: typeof import('./../components/AppHeader.vue')['default']
  const AuthCard: typeof import('./../components/auth/AuthCard.vue')['default']
  const AvatarUploader: typeof import('./../components/common/AvatarUploader.vue')['default']
  const ChatBoard: typeof import('./../components/Chat/ChatBoard.vue')['default']
  const CreateFamilyDialog: typeof import('./../components/Family/CreateFamilyDialog.vue')['default']
  const EditFamilyDialog: typeof import('./../components/Family/EditFamilyDialog.vue')['default']
  const ElCollapse: typeof import('element-plus/es')['ElCollapse']
  const ElCollapseItem: typeof import('element-plus/es')['ElCollapseItem']
  const ElDialog: typeof import('element-plus/es')['ElDialog']
  const ElDropdown: typeof import('element-plus/es')['ElDropdown']
  const ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
  const ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
  const ElInput: typeof import('element-plus/es')['ElInput']
  const ElOption: typeof import('element-plus/es')['ElOption']
  const ElSelect: typeof import('element-plus/es')['ElSelect']
  const ElSkeleton: typeof import('element-plus/es')['ElSkeleton']
  const ElSwitch: typeof import('element-plus/es')['ElSwitch']
  const JoinFamilyDialog: typeof import('./../components/Family/JoinFamilyDialog.vue')['default']
  const RouterLink: typeof import('vue-router')['RouterLink']
  const RouterView: typeof import('vue-router')['RouterView']
  const WelfareCard: typeof import('./../components/welfareCard.vue')['default']
  const WelfareFilterBar: typeof import('./../components/WelfareFilterBar.vue')['default']
}