/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import { GlobalComponents } from 'vue'

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElInput: typeof import('element-plus/es')['ElInput']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    WelfareCard: typeof import('./../components/welfareCard.vue')['default']
    WelfareFilterBar: typeof import('./../components/WelfareFilterBar.vue')['default']
  }
  export interface GlobalDirectives {
    vInfiniteScroll: typeof import('element-plus/es')['ElInfiniteScroll']
  }
}

// For TSX support
declare global {
  const ElDropdown: typeof import('element-plus/es')['ElDropdown']
  const ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
  const ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
  const ElInput: typeof import('element-plus/es')['ElInput']
  const RouterLink: typeof import('vue-router')['RouterLink']
  const RouterView: typeof import('vue-router')['RouterView']
  const WelfareCard: typeof import('./../components/welfareCard.vue')['default']
  const WelfareFilterBar: typeof import('./../components/WelfareFilterBar.vue')['default']
}